### ISSUE TITLE
Unity client

### ISSUE THREAD

**Issue by MexicanMan** [BugsGarage/RicoClient#1]
Мастер тикет по клиенту для Unity

- [x]  #2 - Тикет по авторизации
- [x] #3  - Тикет модального окна ошибок
- [x] #4 - Тикет главного меню
- [x] #7 - Тикет игровой логики
- [x] #9 - Интеграция меню
- [x] #11 - Интеграция игры
- [x] #13 - Баги
